apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ .Chart.Name }}-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
